In [2]:

import numpy as np

matches = np.genfromtxt(
    'matches.csv',
    delimiter=',',
    dtype=None,
    encoding='utf-8',
    names=True,
    missing_values='NA',
    filling_values=None,
    invalid_raise=False
)

print("matches loaded successfully")


FileNotFoundError: matches.csv not found.

In [ ]:
deliveries = np.genfromtxt(
    'deliveries.csv',
    delimiter=',',
    dtype=None,
    encoding='utf-8',
    names=True,
    missing_values='NA',
    filling_values=None,
    invalid_raise=False
)
print("deliveries loaded successfully")

deliveries loaded successfully


In [6]:
match_ids = deliveries['match_id']
batting_team = deliveries['batting_team']
batter = deliveries['batter']
bowler = deliveries['bowler']
batsman_runs = deliveries['batsman_runs']
over = deliveries['over']


TASK 1

In [7]:
print(match_ids[:5])
print(batting_team[:5])
print(batter[:5])
print(bowler[:5])
print(batsman_runs[:5])
print(over[:5])


[335982 335982 335982 335982 335982]
['Kolkata Knight Riders' 'Kolkata Knight Riders' 'Kolkata Knight Riders'
 'Kolkata Knight Riders' 'Kolkata Knight Riders']
['SC Ganguly' 'BB McCullum' 'BB McCullum' 'BB McCullum' 'BB McCullum']
['P Kumar' 'P Kumar' 'P Kumar' 'P Kumar' 'P Kumar']
[0 0 0 0 0]
[0 0 0 0 0]


In [8]:
unique_matches = np.unique(match_ids)

In [9]:
total_runs_per_match = [
    (int(mid), int(np.sum(batsman_runs[match_ids == mid])))
    for mid in np.unique(match_ids)
]

TASK 2


In [10]:
total_runs_per_match

[(335982, 268),
 (335983, 430),
 (335984, 244),
 (335985, 315),
 (335986, 184),
 (335987, 318),
 (335988, 268),
 (335989, 379),
 (335990, 418),
 (335991, 284),
 (335992, 264),
 (335993, 273),
 (335994, 289),
 (335995, 300),
 (335996, 332),
 (335997, 247),
 (335998, 356),
 (335999, 321),
 (336000, 321),
 (336001, 328),
 (336002, 320),
 (336003, 326),
 (336004, 281),
 (336005, 191),
 (336006, 226),
 (336007, 277),
 (336008, 188),
 (336009, 352),
 (336010, 242),
 (336011, 264),
 (336012, 224),
 (336013, 326),
 (336014, 364),
 (336015, 287),
 (336016, 263),
 (336017, 224),
 (336018, 286),
 (336019, 392),
 (336020, 365),
 (336021, 117),
 (336022, 198),
 (336023, 297),
 (336024, 303),
 (336025, 187),
 (336026, 291),
 (336027, 285),
 (336028, 342),
 (336029, 222),
 (336031, 340),
 (336032, 343),
 (336033, 396),
 (336034, 298),
 (336035, 329),
 (336036, 262),
 (336037, 268),
 (336038, 268),
 (336039, 220),
 (336040, 306),
 (392181, 299),
 (392182, 178),
 (392183, 149),
 (392184, 198),
 (392185

In [11]:
unique_batters = np.unique(batter)

In [12]:
total_runs = []

for b in unique_batters:
    runs = np.sum(batsman_runs[batter == b])
    total_runs.append(runs)

total_runs = np.array(total_runs)

In [13]:

top_indices = np.argsort(total_runs)[-5:][::-1]



TASK 3

In [ ]:
top_5_batters = [
    (str(unique_batters[i]), int(total_runs[i]))
    for i in top_indices
]

top_5_batters

[('V Kohli', 8014),
 ('S Dhawan', 6769),
 ('RG Sharma', 6630),
 ('DA Warner', 6567),
 ('SK Raina', 5536)]

TASK 4


In [15]:
import numpy as np

batsman_runs = batsman_runs.astype(int)

unique_batters, inv = np.unique(batter, return_inverse=True)

total_runs = np.zeros(len(unique_batters), dtype=int)
balls_faced = np.zeros(len(unique_batters), dtype=int)

np.add.at(total_runs, inv, batsman_runs)
np.add.at(balls_faced, inv, 1)


strike_rate = np.divide(
    total_runs, balls_faced,
    out=np.zeros_like(total_runs, dtype=float),
    where=balls_faced != 0
) * 100.0


strike_rate_per_batter = [
    (str(unique_batters[i]), float(round(strike_rate[i], 2)))
    for i in range(len(unique_batters))
]

strike_rate_per_batter[:10]


[('A Ashish Reddy', 142.86),
 ('A Badoni', 125.54),
 ('A Chandila', 57.14),
 ('A Chopra', 70.67),
 ('A Choudhary', 125.0),
 ('A Dananjaya', 80.0),
 ('A Flintoff', 108.77),
 ('A Kamboj', 100.0),
 ('A Kumble', 71.43),
 ('A Manohar', 127.62)]

TASK 5

In [16]:
import numpy as np

runs_per_ball = batsman_runs.astype(int)

unique_bowlers, inv = np.unique(bowler, return_inverse=True)

runs_conceded = np.zeros(len(unique_bowlers), dtype=int)
balls_bowled = np.zeros(len(unique_bowlers), dtype=int)

np.add.at(runs_conceded, inv, runs_per_ball)
np.add.at(balls_bowled, inv, 1)

overs_bowled = balls_bowled / 6.0

economy_rate = np.divide(
    runs_conceded,
    overs_bowled,
    out=np.zeros_like(runs_conceded, dtype=float),
    where=overs_bowled != 0
)

economy_per_bowler = [
    (str(unique_bowlers[i]), float(round(economy_rate[i], 2)))
    for i in range(len(unique_bowlers))
]

economy_per_bowler


[('A Ashish Reddy', 8.58),
 ('A Badoni', 8.64),
 ('A Chandila', 6.21),
 ('A Choudhary', 7.61),
 ('A Dananjaya', 11.04),
 ('A Flintoff', 9.55),
 ('A Kamboj', 9.35),
 ('A Kumble', 6.27),
 ('A Mishra', 7.08),
 ('A Mithun', 8.62),
 ('A Nehra', 7.36),
 ('A Nel', 10.33),
 ('A Nortje', 8.33),
 ('A Singh', 7.44),
 ('A Symonds', 7.29),
 ('A Uniyal', 10.11),
 ('A Zampa', 7.72),
 ('AA Chavan', 7.48),
 ('AA Jhunjhunwala', 8.59),
 ('AA Kazi', 9.23),
 ('AA Noffke', 8.4),
 ('AB Agarkar', 8.14),
 ('AB Dinda', 7.5),
 ('AB McDonald', 8.27),
 ('AC Gilchrist', 0.0),
 ('AC Thomas', 7.23),
 ('AC Voges', 7.93),
 ('AD Mascarenhas', 6.83),
 ('AD Mathews', 7.84),
 ('AD Russell', 8.68),
 ('AF Milne', 8.65),
 ('AG Murtaza', 6.78),
 ('AJ Finch', 9.0),
 ('AJ Hosein', 10.0),
 ('AJ Tye', 7.97),
 ('AK Markram', 8.29),
 ('AL Menaria', 7.43),
 ('AM Nayar', 7.81),
 ('AM Rahane', 5.0),
 ('AM Salvi', 7.31),
 ('AN Ahmed', 7.74),
 ('AP Dole', 8.63),
 ('AR Patel', 7.06),
 ('AS Joseph', 8.84),
 ('AS Rajpoot', 8.17),
 ('AS Raut

TASK 6

In [17]:
import numpy as np

overs = over.astype(int)
runs = batsman_runs.astype(int)

total_runs_per_over = np.zeros(20, dtype=int)
balls_per_over = np.zeros(20, dtype=int)

np.add.at(total_runs_per_over, overs, runs)
np.add.at(balls_per_over, overs, 1)

avg_runs_per_over = np.divide(
    total_runs_per_over,
    balls_per_over,
    out=np.zeros(20, dtype=float),
    where=balls_per_over != 0
) * 6.0

avg_runs_per_over.tolist()


[5.347619732489573,
 6.489653670224352,
 7.47253070530264,
 7.739226519337016,
 7.855309734513274,
 7.84393063583815,
 6.260035682426405,
 6.8175725986597175,
 7.128247237981487,
 7.026209375468024,
 7.276394010083527,
 7.4170877007767135,
 7.441688095598245,
 7.725845778725999,
 8.003531941031941,
 8.20125786163522,
 8.53291288923926,
 9.02386751095957,
 9.341103341103342,
 10.024404880976196]

TASK 7

In [18]:
import numpy as np
runs = batsman_runs.astype(int)

num_fours = np.sum(runs == 4)
num_sixes = np.sum(runs == 6)

boundary_counts = {
    "fours": int(num_fours),
    "sixes": int(num_sixes)
}

boundary_counts

{'fours': 29850, 'sixes': 13051}

TASK 8

In [19]:

boundary_mask = (runs == 4) | (runs == 6)

boundary_teams = batting_team[boundary_mask]

unique_teams, inv = np.unique(boundary_teams, return_inverse=True)

boundary_totals = np.zeros(len(unique_teams), dtype=int)
np.add.at(boundary_totals, inv, 1)

top_team = str(unique_teams[np.argmax(boundary_totals)])
top_team_boundaries = int(np.max(boundary_totals))

(top_team, top_team_boundaries)


('Mumbai Indians', 5322)

TASK 9

In [1]:
import numpy as np

overs = over.astype(int)
runs = batsman_runs.astype(int)

death_mask = (overs >= 15) & (overs <= 19)

total_death_runs = int(np.sum(runs[death_mask]))

death_teams = batting_team[death_mask]
death_runs = runs[death_mask]

unique_teams, inv = np.unique(death_teams, return_inverse=True)
team_runs = np.zeros(len(unique_teams), dtype=int)

np.add.at(team_runs, inv, death_runs)

top_team = str(unique_teams[np.argmax(team_runs)])
top_team_runs = int(np.max(team_runs))

(total_death_runs, (top_team, top_team_runs))

NameError: name 'over' is not defined

TASK 10

In [21]:
import numpy as np

match_ids = match_ids.astype(int)
runs = batsman_runs.astype(int)

unique_matches, inv = np.unique(match_ids, return_inverse=True)

match_runs = np.zeros(len(unique_matches), dtype=int)
np.add.at(match_runs, inv, runs)

idx = np.argmax(match_runs)
highest_scoring_match = (int(unique_matches[idx]), int(match_runs[idx]))

highest_scoring_match

(1426268, 520)

TASK 11

In [22]:
import numpy as np

m_ids = match_ids.astype(int)
runs = batsman_runs.astype(int)
teams = batting_team.astype(str)

match_team_pairs = np.column_stack((m_ids, teams))

unique_pairs, inv = np.unique(match_team_pairs, axis=0, return_inverse=True)

team_match_runs = np.zeros(len(unique_pairs), dtype=int)
np.add.at(team_match_runs, inv, runs)

unique_matches = np.unique(m_ids)
match_winners = []

for mid in unique_matches:
    mask = unique_pairs[:, 0].astype(int) == mid
    teams_in_match = unique_pairs[mask][:, 1]
    scores = team_match_runs[mask]
    winner = teams_in_match[np.argmax(scores)]
    match_winners.append((int(mid), str(winner)))

match_winners

[(335982, 'Kolkata Knight Riders'),
 (335983, 'Chennai Super Kings'),
 (335984, 'Delhi Daredevils'),
 (335985, 'Royal Challengers Bangalore'),
 (335986, 'Deccan Chargers'),
 (335987, 'Kings XI Punjab'),
 (335988, 'Deccan Chargers'),
 (335989, 'Chennai Super Kings'),
 (335990, 'Rajasthan Royals'),
 (335991, 'Kings XI Punjab'),
 (335992, 'Rajasthan Royals'),
 (335993, 'Kolkata Knight Riders'),
 (335994, 'Deccan Chargers'),
 (335995, 'Kings XI Punjab'),
 (335996, 'Chennai Super Kings'),
 (335997, 'Kolkata Knight Riders'),
 (335998, 'Delhi Daredevils'),
 (335999, 'Kings XI Punjab'),
 (336000, 'Rajasthan Royals'),
 (336001, 'Delhi Daredevils'),
 (336002, 'Royal Challengers Bangalore'),
 (336003, 'Kings XI Punjab'),
 (336004, 'Mumbai Indians'),
 (336005, 'Chennai Super Kings'),
 (336006, 'Royal Challengers Bangalore'),
 (336007, 'Deccan Chargers'),
 (336008, 'Rajasthan Royals'),
 (336009, 'Chennai Super Kings'),
 (336010, 'Kolkata Knight Riders'),
 (336011, 'Deccan Chargers'),
 (336012, 'Mum

TASK 12

In [25]:
import numpy as np

del_match_ids = match_ids.astype(int)
runs = batsman_runs.astype(int)
teams = batting_team.astype(str)

match_ids_m = matches['id'].astype(int)
toss_winners = matches['toss_winner'].astype(str)

match_team_pairs = np.column_stack((del_match_ids, teams))
unique_pairs, inv = np.unique(match_team_pairs, axis=0, return_inverse=True)

team_match_runs = np.zeros(len(unique_pairs), dtype=int)
np.add.at(team_match_runs, inv, runs)

toss_impact = []

for mid, toss_winner in zip(match_ids_m, toss_winners):
    mask = unique_pairs[:, 0].astype(int) == mid

    if np.sum(mask) != 2:
        continue

    teams_in_match = unique_pairs[mask][:, 1]
    scores = team_match_runs[mask]

    toss_runs = scores[teams_in_match == toss_winner]
    opp_runs = scores[teams_in_match != toss_winner]

    if len(toss_runs) == 0 or len(opp_runs) == 0:
        continue

    toss_impact.append(
        (int(mid), str(toss_winner), int(toss_runs[0]), int(opp_runs[0]),
         bool(toss_runs[0] > opp_runs[0])
    ))

toss_impact

[(335982, 'Royal Challengers Bangalore', 63, 205, False),
 (335984, 'Rajasthan Royals', 122, 122, False),
 (335985, 'Mumbai Indians', 154, 161, False),
 (335986, 'Deccan Chargers', 100, 84, True),
 (335987, 'Kings XI Punjab', 162, 156, True),
 (335992, 'Rajasthan Royals', 135, 129, True),
 (335994, 'Deccan Chargers', 146, 143, True),
 (335996, 'Chennai Super Kings', 174, 158, True),
 (335997, 'Kolkata Knight Riders', 124, 123, True),
 (335998, 'Royal Challengers Bangalore', 169, 187, False),
 (336000, 'Rajasthan Royals', 182, 139, True),
 (336034, 'Deccan Chargers', 147, 151, False),
 (336004, 'Delhi Daredevils', 129, 152, False),
 (336005, 'Chennai Super Kings', 102, 89, True),
 (336006, 'Kings XI Punjab', 110, 116, False),
 (336008, 'Mumbai Indians', 92, 96, False),
 (336009, 'Chennai Super Kings', 177, 175, True),
 (336010, 'Kolkata Knight Riders', 124, 118, True),
 (336011, 'Rajasthan Royals', 130, 134, False),
 (336015, 'Rajasthan Royals', 142, 145, False),
 (336017, 'Kolkata Knig

TASK 13


In [24]:
import numpy as np

m_ids = match_ids.astype(int)
runs = batsman_runs.astype(int)
teams = batting_team.astype(str)

match_team_pairs = np.column_stack((m_ids, teams))
unique_pairs, inv = np.unique(match_team_pairs, axis=0, return_inverse=True)

team_runs = np.zeros(len(unique_pairs), dtype=int)
np.add.at(team_runs, inv, runs)

unique_matches = np.unique(m_ids)
scorecards = []

for mid in unique_matches:
    mask = unique_pairs[:, 0].astype(int) == mid
    teams_in_match = unique_pairs[mask][:, 1]
    runs_in_match = team_runs[mask]

    if len(teams_in_match) != 2:
        continue

    scorecards.append(
        f"""Match {mid}:
 {teams_in_match[0]}: {int(runs_in_match[0])} runs
 {teams_in_match[1]}: {int(runs_in_match[1])} runs"""
    )

print("\n\n".join(scorecards))


Match 335982:
 Kolkata Knight Riders: 205 runs
 Royal Challengers Bangalore: 63 runs

Match 335983:
 Chennai Super Kings: 234 runs
 Kings XI Punjab: 196 runs

Match 335984:
 Delhi Daredevils: 122 runs
 Rajasthan Royals: 122 runs

Match 335985:
 Mumbai Indians: 154 runs
 Royal Challengers Bangalore: 161 runs

Match 335986:
 Deccan Chargers: 100 runs
 Kolkata Knight Riders: 84 runs

Match 335987:
 Kings XI Punjab: 162 runs
 Rajasthan Royals: 156 runs

Match 335988:
 Deccan Chargers: 137 runs
 Delhi Daredevils: 131 runs

Match 335989:
 Chennai Super Kings: 190 runs
 Mumbai Indians: 189 runs

Match 335990:
 Deccan Chargers: 208 runs
 Rajasthan Royals: 210 runs

Match 335991:
 Kings XI Punjab: 175 runs
 Mumbai Indians: 109 runs

Match 335992:
 Rajasthan Royals: 135 runs
 Royal Challengers Bangalore: 129 runs

Match 335993:
 Chennai Super Kings: 134 runs
 Kolkata Knight Riders: 139 runs

Match 335994:
 Deccan Chargers: 146 runs
 Mumbai Indians: 143 runs

Match 335995:
 Delhi Daredevils: 147 